#!/usr/bin/env bash

array=(foo bar baz)

for item in "${array[*]}"; do
	echo "item is: $item"
done

for item in "$array"; do
	echo "item is: $item"
done

for item in "${array[@]}"; do
	echo "item is: $item"
done
